"""add_image_url_to_comments

Revision ID: 7388fcc87f04
Revises: b89fab7ee48a
Create Date: 2026-05-07 01:42:28.943622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7388fcc87f04'
down_revision: Union[str, Sequence[str], None] = 'b89fab7ee48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'image_url')
    # ### end Alembic commands ###
